# Generated by Selenium IDE
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.options import Options

STATIC_URL = "http://18.219.95.140:8000/"
WAIT_TIME = 3

class TestDefaultSuite():
  def setup_method(self, method):
    options = Options()
    options.add_argument("-headless")  # Runs Firefox without a GUI window
    self.driver = webdriver.Firefox(options=options)
    self.driver.set_window_size(1920, 1080)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createaccount(self):
    file_path = os.path.abspath("IMCreate/testing/profilepic.jpg")

    # navigation
    self.driver.get(STATIC_URL)
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.CSS_SELECTOR, ".content").click()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(1)").click()

    # username
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("testuser2")
    
    # password
    self.driver.find_element(By.ID, "id_password1").send_keys("userpass")
    self.driver.find_element(By.ID, "id_password2").click()
    self.driver.find_element(By.ID, "id_password2").send_keys("userpass")

    # submit
    self.driver.find_element(By.CSS_SELECTOR, "button").click()

    # wait
    wait = WebDriverWait(self.driver, WAIT_TIME)
    about_me_field = wait.until(EC.presence_of_element_located((By.ID, "id_about_me")))
    about_me_field.click()

    # about me
    self.driver.find_element(By.ID, "id_about_me").send_keys("this is a blurb about me")

    # profile pic
    self.driver.find_element(By.ID, "id_profile_pic").send_keys(file_path)
    
    # submit
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
  def test_createpost(self):
    file_path = os.path.abspath("IMCreate/testing/furby.jpg")

    # navigation
    self.driver.get(STATIC_URL)
    self.driver.find_element(By.LINK_TEXT, "Make Post").click()

    # post title
    self.driver.find_element(By.ID, "id_title").click()
    self.driver.find_element(By.ID, "id_title").send_keys("test post1")
    
    # post description
    self.driver.find_element(By.ID, "id_description").click()
    self.driver.find_element(By.ID, "id_description").send_keys("this is the description of the test post")
    
    # post tags
    self.driver.find_element(By.ID, "id_tags").click()
    self.driver.find_element(By.ID, "id_tags").send_keys("test, selenium")
    
    # post picture
    self.driver.find_element(By.ID, "id_images").send_keys(file_path)
    
    # submit
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
  def test_editprofile(self):
    file_path = os.path.abspath("IMCreate/testing/rabbit.jpg")

    # navigation
    self.driver.get(STATIC_URL)
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    
    # log in
    self.driver.find_element(By.ID, "id_username").send_keys("testuser2")
    self.driver.find_element(By.ID, "id_password").send_keys("userpass")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()

    # change About Me
    self.driver.find_element(By.ID, "id_about_me").click()
    self.driver.find_element(By.ID, "id_about_me").send_keys("this is an edited about me")
    
    # change profile pic
    self.driver.find_element(By.ID, "id_profile_pic").send_keys(file_path)

    # submit
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
  def test_tagsearch(self):

    #navigation
    self.driver.get(STATIC_URL)
    self.driver.find_element(By.ID, "tags").click()

    # tag search
    self.driver.find_element(By.ID, "tags").send_keys("first")
    self.driver.find_element(By.ID, "tags").send_keys(Keys.ENTER)



# wait = WebDriverWait(self.driver, WAIT_TIME)
# id_display_field = wait.until(EC.presence_of_element_located((By.ID, "id_display_name")))
# id_display_field.click()

# wait = WebDriverWait(self.driver, 10)
# name_element = wait.until(EC.presence_of_element_located((By.ID, "name")))
# name_text = name_element.text print(f'name_text: {name_text}')
# assert "Candice Batton" in name_text, f"Expected 'Candice Batton' in search results, but got '{name_text}'"