# Generated by Selenium IDE
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.options import Options

STATIC_URL = "http://3.17.12.41:8000/"
WAIT_TIME = 3
TEST_USER = 4

class TestDefaultSuite():
  def setup_method(self, method):
    options = Options()
    options.add_argument("-headless")  # Runs Firefox without a GUI window
    self.driver = webdriver.Firefox(options=options)
    self.driver.set_window_size(1920, 1080)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
    
  def test_edit_profilepic(self):
   # Requires valid testuser# and picture
    file_path = os.path.abspath("IMCreate/testing/rabbit.jpg")

    # navigation
    self.driver.get(STATIC_URL)
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    
    # log in
    self.driver.find_element(By.ID, "id_username").send_keys(f"testuser{TEST_USER}")
    self.driver.find_element(By.ID, "id_password").send_keys("userpass")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()
    
    # change profile pic
    self.driver.find_element(By.ID, "id_profile_pic").send_keys(file_path)

    # submit
    self.driver.find_element(By.CSS_SELECTOR, "button").click()

  def test_edit_aboutme(self):
   # Requires valid testuser#

    # navigation
    self.driver.get(STATIC_URL)
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    
    # log in
    self.driver.find_element(By.ID, "id_username").send_keys(f"testuser{TEST_USER}")
    self.driver.find_element(By.ID, "id_password").send_keys("userpass")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()

    # change About Me
    self.driver.find_element(By.ID, "id_about_me").send_keys(" This is an added edit.")
    
    # submit
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
  def test_tagsearch(self):

    #navigation
    self.driver.get(STATIC_URL)
    self.driver.find_element(By.ID, "tags").click()

    # tag search
    self.driver.find_element(By.ID, "tags").send_keys("first")
    self.driver.find_element(By.ID, "tags").send_keys(Keys.ENTER)

  def test_like(self):
    # Requires at least one post on Home
    
    # navigation
    self.driver.get(STATIC_URL)
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    
    # login
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("testuser4")
    self.driver.find_element(By.ID, "id_password").send_keys("userpass")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()

    # navigate to post
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.CSS_SELECTOR, ".post_container:nth-child(3) .post_image").click()
    
    # like
    self.driver.find_element(By.CSS_SELECTOR, "#like-btn-8 > svg").click()
  
  def test_pagination(self):
    # Requires at least 2 pages on Home
    self.driver.get(STATIC_URL)
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Next Page »").click()
  
  def test_viewprofile(self):
    self.driver.get(STATIC_URL)
    self.driver.find_element(By.CSS_SELECTOR, ".post_container:nth-child(3) .user > div").click()