# Generated by Selenium IDE
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.options import Options

STATIC_URL = "http://3.17.12.41:8000/"
WAIT_TIME = 3
TEST_USER = 6 # increase every test

class TestDefaultSuite():
  def setup_method(self, method):
    options = Options()
    options.add_argument("-headless")  # Runs Firefox without a GUI window
    self.driver = webdriver.Firefox(options=options)
    self.driver.set_window_size(1920, 1080)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createaccount(self):
   # Requires testuser# to be unused
    file_path = os.path.abspath("IMCreate/testing/profilepic.jpg")
    wait = WebDriverWait(self.driver, WAIT_TIME)

    # navigation
    self.driver.get(STATIC_URL)
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.CSS_SELECTOR, ".content").click()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(1)").click()

    # username
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys(f"testuser{TEST_USER}")
    
    # password
    self.driver.find_element(By.ID, "id_password1").send_keys("userpass")
    self.driver.find_element(By.ID, "id_password2").click()
    self.driver.find_element(By.ID, "id_password2").send_keys("userpass")

    # submit
    self.driver.find_element(By.CSS_SELECTOR, "button").click()

    # wait
    wait_field = wait.until(EC.presence_of_element_located((By.ID, "id_about_me")))
    wait_field.click()

    # about me
    self.driver.find_element(By.ID, "id_about_me").send_keys("This is a blurb about me.")

    # profile pic
    self.driver.find_element(By.ID, "id_profile_pic").send_keys(file_path)
    
    # submit
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
  def test_createpost(self):
    # Requires valid testuser# and picture
    file_path = os.path.abspath("IMCreate/testing/furby.jpg")

    # navigation
    self.driver.get(STATIC_URL)
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    
    # log in
    self.driver.find_element(By.ID, "id_username").send_keys(f"testuser{TEST_USER}")
    self.driver.find_element(By.ID, "id_password").send_keys("userpass")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()

    # navigation
    self.driver.find_element(By.LINK_TEXT, "Make Post").click()

    # post title
    self.driver.find_element(By.ID, "id_title").click()
    self.driver.find_element(By.ID, "id_title").send_keys("test post")
    
    # post description
    self.driver.find_element(By.ID, "id_description").click()
    self.driver.find_element(By.ID, "id_description").send_keys("this is the description of the test post")
    
    # post tags
    self.driver.find_element(By.ID, "id_tags").click()
    self.driver.find_element(By.ID, "id_tags").send_keys("test, selenium")
    
    # post picture
    self.driver.find_element(By.ID, "id_images").send_keys(file_path)
    
    # submit
    self.driver.find_element(By.CSS_SELECTOR, "button").click()

  def test_block(self):
    # Requires first post to not be blocked or followed
    
    # navigation
    self.driver.get(STATIC_URL)
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    
    # login
    self.driver.find_element(By.ID, "id_username").send_keys(f"testuser{TEST_USER}")
    self.driver.find_element(By.ID, "id_password").send_keys("userpass")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)

    # block link
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.CSS_SELECTOR, ".post_form:nth-child(2) > button").click()
  
  def test_follow(self):
    # Requires first post on Home to not be previously followed

    # navigation
    self.driver.get(STATIC_URL)
    self.driver.find_element(By.LINK_TEXT, "Profile").click()

    # login
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys(f"testuser{TEST_USER}")
    self.driver.find_element(By.ID, "id_password").send_keys("userpass")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()

    # follow link
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.CSS_SELECTOR, ".content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".post_form:nth-child(1) > button").click()

 