# Generated by Django 5.2.11 on 2026-03-31 05:58

import IMCreate.image_upload
import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('about_me', models.TextField(blank=True, max_length=1000)),
                ('profile_pic', django_resized.forms.ResizedImageField(blank=True, crop=['top', 'left'], force_format='JPEG', keep_meta=True, null=True, quality=50, scale=None, size=[150, 150], upload_to=IMCreate.image_upload.pfp_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
